# Generated by Django 3.2 on 2021-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='done',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Done', 'Done')], max_length=5),
        ),
    ]
