# Generated by Django 3.2 on 2021-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_login_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='description',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='login',
            name='password01',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='login',
            name='password02',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
