# Generated by Django 3.2 on 2021-04-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_auto_20210424_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Tasks'},
        ),
    ]
